version: 2
jobs:
  build:
    docker:
      - image: docker:17.09.1-ce
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Prepare QEMU
          command: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run:
          name: Build darkmane/pytivo-rpi
          command: docker build -t darkmane/pytivo-rpi -f Dockerfile-rpi .
      - run:
          name: Test image
          command: echo No tests for this image
      - run:
          name: Tag docker image
          command: docker tag darkmane/pytivo-rpi darkmane/pytivo-rpi:$CIRCLE_SHA1
      - run:
          name: Push image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push  darkmane/pytivo-rpi:$CIRCLE_SHA1
